// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw--FwUL-h2n9vXBf8XWNL-yIBRsftjFY',
    appId: '1:343482645477:web:c6cf6fe05897b1b35b0d0c',
    messagingSenderId: '343482645477',
    projectId: 'biblioteca-ce6d2',
    authDomain: 'biblioteca-ce6d2.firebaseapp.com',
    storageBucket: 'biblioteca-ce6d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0iToH3UGI3CEHiAUDgQkinZOhB34fSYo',
    appId: '1:343482645477:android:d1b7458d94b0f5e95b0d0c',
    messagingSenderId: '343482645477',
    projectId: 'biblioteca-ce6d2',
    storageBucket: 'biblioteca-ce6d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbQfTr8ePoVoJgAs1HTuwXd23xjwksJKU',
    appId: '1:343482645477:ios:0d0bd7df1a0c91905b0d0c',
    messagingSenderId: '343482645477',
    projectId: 'biblioteca-ce6d2',
    storageBucket: 'biblioteca-ce6d2.firebasestorage.app',
    iosBundleId: 'com.example.infomeBiblioteca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbQfTr8ePoVoJgAs1HTuwXd23xjwksJKU',
    appId: '1:343482645477:ios:0d0bd7df1a0c91905b0d0c',
    messagingSenderId: '343482645477',
    projectId: 'biblioteca-ce6d2',
    storageBucket: 'biblioteca-ce6d2.firebasestorage.app',
    iosBundleId: 'com.example.infomeBiblioteca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw--FwUL-h2n9vXBf8XWNL-yIBRsftjFY',
    appId: '1:343482645477:web:2b78ca5c2c09537c5b0d0c',
    messagingSenderId: '343482645477',
    projectId: 'biblioteca-ce6d2',
    authDomain: 'biblioteca-ce6d2.firebaseapp.com',
    storageBucket: 'biblioteca-ce6d2.firebasestorage.app',
  );
}
